### ISSUE TITLE
[Feat]: Add Hover Effect to Social Links with Color Corresponding to Their Social Colors

### ISSUE THREAD

**Issue by abhiperfect** [TechNodes2-0/ElectiveHub#95] opened 2024-05-11 20:24 UTC
### Is your feature request related to a problem? Please describe.

No, the feature request is not related to a problem. It's about enhancing the visual appeal and user experience of the social links on the website by adding a hover effect that changes the color according to the respective social media platforms.

### Describe the solution you'd like.

I'd like to have a hover effect added to the social links on the website. When a user hovers over a social link, the color of the icon or background should change to match the corresponding color of the social media platform. This will provide a visually appealing and intuitive experience for users interacting with the social links.

### Show us the magic with screenshots

https://github.com/TechNodes2-0/ElectiveHub/assets/114478676/eca02a11-a91a-45b3-a077-e6a9a0cc410d

### Checklist

- [X] I have checked the [existing issues](https://github.com/TechNodes2-0/ElectiveHub/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/TechNodes2-0/ElectiveHub/blob/main/CONTRIBUTING.md)
- [X] I want to work on this issue. (optional)

**Comment by Yash636261** [comment] 2024-05-12 04:04
The issue is already mentioned and assigned, so I'm closing this one.

**Closed** 2024-05-12 04:05 UTC
